#!/bin/bash

WEB_DIR="/Users/Santiago/github/local/PalermoTenis/build/web"
JS_DIR="$WEB_DIR/js"
ADMINJS_DIR="$WEB_DIR/admin/js"

JQUERY_DIR="$JS_DIR/jquery"
JQUERY_SRC="$JQUERY_DIR/src"
JQUERY_PACK="$JQUERY_DIR/pack"

JQUERYUI_DIR="$JQUERY_DIR/ui"
JQUERYUI_SRC="$JQUERYUI_DIR/src"
JQUERYUI_PACK="$JQUERYUI_DIR/pack"

JSMAIN_DIR="$JS_DIR/main"
JSMAIN_SRC="$JSMAIN_DIR/src"
JSMAIN_PACK="$JSMAIN_DIR/pack"

JSADMIN_SRC="$ADMINJS_DIR/src"
JSADMIN_PACK="$ADMINJS_DIR/pack"

JPACKER_JAR="/Users/Santiago/NetBeansProjects/trunk/jpacker/dist/jpacker.jar"
PACKED_EXT="pack.js"
UNPACKED_EXT="unpacked.js"

compress () {
	for jsfile in $1/*.js; do
		new_name=`basename $jsfile .js`.$PACKED_EXT
		echo "Compressing $new_name ..."
		java -jar $JPACKER_JAR -q -s -b 62 $jsfile | iconv -t iso-8859-1 > $2/$new_name
	done
}

compress $JSMAIN_SRC $JSMAIN_PACK

for subfolder in $JSADMIN_SRC/*; do
	for jsfile in $subfolder/*.js; do
		new_dir=$JSADMIN_PACK/`basename $subfolder`
		new_name=`basename $jsfile .js`.$PACKED_EXT
		echo "Compressing $new_name ..."
		java -jar $JPACKER_JAR -q -s -b 62 $jsfile | iconv -t iso-8859-1 > $new_dir/$new_name
	done
done


echo "Compressing jQuery and its plugins..."
compress $JQUERY_SRC $JQUERY_PACK
compress $JQUERY_SRC/jqgrid $JQUERY_PACK

echo "Compressing jQuery UI and its plugins..."
compress $JQUERYUI_SRC $JQUERYUI_PACK
