var xhr;function principalCallback(){$("#menu-principal .loader").hide();$("#principal li.selectable").click(function(){$(this).addClass("selected");var a=$(this).attr("id"),c=$(this).parent().parent().attr("id"),a=("marca:"+a+"_tipoProducto:"+c).replace(/^.*#/,"");$.historyLoad(a);return!1})}
function createTreeView(a,c){$("#menu-secundario").show("slow").find(".loader").show();$("#secundario").remove();$("#menu-secundario").append($("\x3cul id\x3d'secundario'\x3e\x3c/ul\x3e").treeview({url:"ListarModelos_listActive",parameters:{idMarca:a,idTipoProducto:c},treeType:"modelos",animated:"normal",unique:!1,persist:"location",success:secundarioCallback}))}
function secundarioCallback(){$("#menu-secundario .loader").hide();$("#secundario li.selectable").click(function(){var a=$("#principal li.active").attr("id"),c=$("#principal li.active").parents("li:first").attr("id"),a="marca:"+a+"_tipoProducto:"+c+"_modelo:"+$(this).attr("id");$.historyLoad(a);return!1})}
function loadProducto(a,c,d){$("#menu-secundario").is(":hidden")&&createTreeView(c,d);$("#contenidos .loader").show();void 0!==xhr&&xhr.abort();xhr=$.ajax({url:"MostrarProducto",data:{id:a},success:function(b){$("#contenidos .central").html(b);$("#contenidos .loader").hide();$(".producto-precio a").click(function(){cotizacion($(this).parent().parent())});activate(d,c,a);expand(d,a)}})}
function loadMiniaturas(a){$("#contenidos .loader").show();$("#contenidos .central").empty();void 0!==xhr&&xhr.abort();xhr=$.ajax({url:"MostrarMiniaturas_showByPadre",data:{modeloId:a},success:function(a){$("#contenidos .central").html(a);$("#contenidos .loader").hide()}})}
function loadMiniaturasByMarca(a,c){$("#contenidos .loader").show();$("#contenidos .central").empty();void 0!==xhr&&xhr.abort();xhr=$.ajax({url:"MostrarMiniaturas_showByMarca",data:{tipoProductoId:a,marcaId:c},success:function(a){$("#contenidos .central").html(a);$("#contenidos .loader").hide()}})}
function cotizacion(a){startTime=new Date;var c=setInterval("currentTime()",100),d={2:{symbol:"U$S",code:"USD",name:"Dolares",contraryID:1,contrarySymbol:"$",contraryCode:"ARS",contraryName:"Pesos"},1:{symbol:"AR$",code:"ARS",name:"Pesos",contraryID:2,contrarySymbol:"U$D",contraryCode:"USD",contraryName:"Dolares"}},b=a.find(".moneda"),e=a.find(".valor-hidden"),g=a.find(".valor span"),f=a.find(".convertir strong"),h=d[trim(b.val())].code,i=d[trim(b.val())].contraryCode,j=a.find(".cotLoader").show();
$.ajax({type:"GET",url:"GetCotizacion",data:"from\x3d"+h+"\x26to\x3d"+i,cache:!1,success:function(a){if(isNaN(a))alert("El servicio no se encuentra disponible en este momento.\nVuelva a intentar más tarde.");else{_gaq.push(["_trackEvent","Moneda","Convertir","De "+d[trim(b.val())].name+" a "+d[trim(b.val())].contraryName]);var h=d[trim(b.val())].contrarySymbol;$.each(e,function(){var b=parseFloat($(this).val()),b=b*parseFloat(a);$(this).val(b)});$.each(g,function(){var b=parseFloat(trim($(this).text().replace(/[\\$|U\\$D]/gi,
""))),b=b*parseFloat(a);$(this).html(formatCurrency(b,h))});f.html(" "+d[trim(b.val())].name+" "+d[trim(b.val())].symbol);b.val(d[trim(b.val())].contraryID)}j.hide();clearTimeout(c)}})}function formatCurrency(a,c){a=a.toString().replace(/\$|\,/g,"");isNaN(a)&&(a="0");a=Math.floor(100*a+0.50000000001);var d=a%100;a=Math.floor(a/100).toString();10>d&&(d="0"+d);for(var b=0;b<Math.floor((a.length-(1+b))/3);b++)a=a.substring(0,a.length-(4*b+3))+","+a.substring(a.length-(4*b+3));return c+a+"."+d}
function ltrim(a){return a.replace(/^\s+/,"")}function rtrim(a){return a.replace(/\s+$/,"")}function trim(a){return rtrim(ltrim(a))}function activate(a,c,d){$("#principal .active").removeClass("active");$("#principal").find("li#"+a).find("li#"+c).addClass("active");d&&($("#secundario .active").removeClass("active"),$("#secundario").find("li#"+d).addClass("active"))}
function expand(a,c){var d=$("#principal").find("li#"+a);d.hasClass("expandable")&&d.find("div.hitarea").click();c&&expandNode($("#secundario").find("li#"+c).parents("li:last").contents())}function expandNode(a){a.each(function(){$(this).hasClass("expandable")?$(this).find("div.hitarea").click():$(this).parent().hasClass("expandable")?$(this).parent().find("div.hitarea").click():$(this).is("ul")&&expandNode($(this).children())})}
function pageload(a){if(a){a=new String(a);a=a.split("_");for(var c=0;c<a.length;c++){var d=a[c].split(":",2);if("marca"==d[0])var b=d[1];else if("tipoProducto"==d[0])var e=d[1];else if("modelo"==d[0])var g=d[1]}isNaN(b)||isNaN(e)?window.location.href="/":g?isNaN(g)?window.location.href="/":($("#contenidos .central").empty(),loadProducto(g,b,e)):(createTreeView(b,e),loadMiniaturasByMarca(e,b),activate(e,b),expand(e))}else $("#menu-secundario").hide(),$("#contenidos").addClass("loading"),void 0!==
xhr&&xhr.abort(),xhr=$.ajax({url:"/MostrarOfertas",success:function(a){$("#contenidos .central").html(a);$("#contenidos").removeClass("loading")}})}
$(document).ready(function(){$.historyInit(pageload,"index.jsp");$("#menu-principal .loader").show();$("#principal").treeview({url:"ListarTipoProductos",id:0,treeType:"tiposProducto",animated:"normal",unique:!0,persist:"location",success:principalCallback});-1==(new String(window.location.href)).indexOf("#")&&pageload("");$("#buscar-flecha").click(function(){$("#news-cartel").hide();var a=$("#buscar-texto").val();if(a&&!(""==a||"NEWSLETTER"==a))/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/.test(a)?
($("#news-loader").show(),$.getJSON("/newsletter/AgregarSuscriptor",{email:a},function(a){$("#news-loader").hide();$("#news-cartel").html(a.msg).show("slow")})):$("#news-cartel").html("Por favor, asegurese que ha ingresado una dirección de correo válida.").show("slow")});$("#buscar-texto").keydown(function(a){13==a.keyCode&&$("#buscar-flecha").click()})});
var isIE=-1!=navigator.appVersion.indexOf("MSIE")?!0:!1,isWin=-1!=navigator.appVersion.toLowerCase().indexOf("win")?!0:!1,isOpera=-1!=navigator.userAgent.indexOf("Opera")?!0:!1;function MM_swapImgRestore(){var a,c,d=document.MM_sr;for(a=0;d&&a<d.length&&(c=d[a])&&c.oSrc;a++)c.src=c.oSrc}
function MM_preloadImages(){var a=document;if(a.images){a.MM_p||(a.MM_p=[]);var c,d=a.MM_p.length,b=MM_preloadImages.arguments;for(c=0;c<b.length;c++)0!=b[c].indexOf("#")&&(a.MM_p[d]=new Image,a.MM_p[d++].src=b[c])}}
function MM_findObj(a,c){var d,b;c||(c=document);if(0<(d=a.indexOf("?"))&&parent.frames.length)c=parent.frames[a.substring(d+1)].document,a=a.substring(0,d);if(!(b=c[a])&&c.all)b=c.all[a];for(d=0;!b&&d<c.forms.length;d++)b=c.forms[d][a];for(d=0;!b&&c.layers&&d<c.layers.length;d++)b=MM_findObj(a,c.layers[d].document);!b&&c.getElementById&&(b=c.getElementById(a));return b}
function MM_swapImage(){var a,c=0,d,b=MM_swapImage.arguments;document.MM_sr=[];for(a=0;a<b.length-2;a+=3)if(null!=(d=MM_findObj(b[a])))document.MM_sr[c++]=d,d.oSrc||(d.oSrc=d.src),d.src=b[a+2]}
function ControlVersion(){var a,c;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a=c.GetVariable("$version")}catch(d){}if(!a)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a="WIN 6,0,21,0",c.AllowScriptAccess="always",a=c.GetVariable("$version")}catch(b){}if(!a)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a=c.GetVariable("$version")}catch(e){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a="WIN 3,0,18,0"}catch(g){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),
a="WIN 2,0,0,11"}catch(f){a=-1}return a}
function GetSwfVer(){var a=-1;if(null!=navigator.plugins&&0<navigator.plugins.length){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var a=navigator.plugins["Shockwave Flash"+(navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"")].description.split(" "),c=a[2].split("."),d=c[0],c=c[1],b=a[3];""==b&&(b=a[4]);"d"==b[0]?b=b.substring(1):"r"==b[0]&&(b=b.substring(1),0<b.indexOf("d")&&(b=b.substring(0,b.indexOf("d"))));a=d+"."+c+"."+b}}else-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.6")?
a=4:-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.5")?a=3:-1!=navigator.userAgent.toLowerCase().indexOf("webtv")?a=2:isIE&&(isWin&&!isOpera)&&(a=ControlVersion());return a}
function DetectFlashVer(a,c,d){versionStr=GetSwfVer();if(-1==versionStr)return!1;if(0!=versionStr){isIE&&isWin&&!isOpera?(tempArray=versionStr.split(" "),tempString=tempArray[1],versionArray=tempString.split(",")):versionArray=versionStr.split(".");var b=versionArray[0],e=versionArray[1],g=versionArray[2];return b>parseFloat(a)||b==parseFloat(a)&&(e>parseFloat(c)||e==parseFloat(c)&&g>=parseFloat(d))?!0:!1}}function AC_AddExtension(a,c){return-1!=a.indexOf("?")?a.replace(/\?/,c+"?"):a+c}
function AC_Generateobj(a,c,d){var b="";if(isIE&&isWin&&!isOpera){var b=b+"\x3cobject ",e;for(e in a)b+=e+'\x3d"'+a[e]+'" ';b+="\x3e";for(e in c)b+='\x3cparam name\x3d"'+e+'" value\x3d"'+c[e]+'" /\x3e ';b+="\x3c/object\x3e"}else{b+="\x3cembed ";for(e in d)b+=e+'\x3d"'+d[e]+'" ';b+="\x3e \x3c/embed\x3e"}document.write(b)}
function AC_FL_RunContent(){var a=AC_GetArgs(arguments,".swf","movie","clsid:d27cdb6e-ae6d-11cf-96b8-444553540000","application/x-shockwave-flash");AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}function AC_SW_RunContent(){var a=AC_GetArgs(arguments,".dcr","src","clsid:166B1BCA-3F9C-11CF-8075-444553540000",null);AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}
function AC_GetArgs(a,c,d,b,e){for(var g={embedAttrs:{},params:{},objAttrs:{}},f=0;f<a.length;f+=2)switch(a[f].toLowerCase()){case "classid":break;case "pluginspage":g.embedAttrs[a[f]]=a[f+1];break;case "src":case "movie":a[f+1]=AC_AddExtension(a[f+1],c);g.embedAttrs.src=a[f+1];g.params[d]=a[f+1];break;case "onafterupdate":case "onbeforeupdate":case "onblur":case "oncellchange":case "onclick":case "ondblClick":case "ondrag":case "ondragend":case "ondragenter":case "ondragleave":case "ondragover":case "ondrop":case "onfinish":case "onfocus":case "onhelp":case "onmousedown":case "onmouseup":case "onmouseover":case "onmousemove":case "onmouseout":case "onkeypress":case "onkeydown":case "onkeyup":case "onload":case "onlosecapture":case "onpropertychange":case "onreadystatechange":case "onrowsdelete":case "onrowenter":case "onrowexit":case "onrowsinserted":case "onstart":case "onscroll":case "onbeforeeditfocus":case "onactivate":case "onbeforedeactivate":case "ondeactivate":case "type":case "codebase":case "id":g.objAttrs[a[f]]=
a[f+1];break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "tabindex":g.embedAttrs[a[f]]=g.objAttrs[a[f]]=a[f+1];break;default:g.embedAttrs[a[f]]=g.params[a[f]]=a[f+1]}g.objAttrs.classid=b;e&&(g.embedAttrs.type=e);return g};